config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :caption, presence: true
    validates :image, presence: true

    has_attached_file :image, styles: { :large => "855x570>", :medium => "432x288>", :small => "276x184>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :validate_url_id, only: [:edit, :update, :destroy]

    def index
        #@posts = Post.all
        @posts = Post.order(updated_at: :desc).paginate(page: params[:page], per_page: 3)
    end

    def new
        @post = Post.new
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            flash[:success] = "Post updated."
            redirect_to posts_path
        else
            render 'edit'
        end
    end

    def create
        @post = Post.new(post_params)
        if @post.save()
            flash[:success] = "Post created."
            redirect_to posts_path
        else
            render 'new'
        end
    end

    def destroy
        post = Post.find(params[:id])
        if post.destroy
            flash[:success] = "Post deleted."
        else
            flash[:error] = "Post could not be deleted."
        end
        redirect_to posts_path
    end

    private

    def post_params
        params.require(:post).permit(:image, :caption)
    end

    def validate_url_id
        if !Post.exists?(params[:id])
            redirect_to posts_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "flash-messages">
      <% flash.each do |type, msg| %>
        <div>
          <%= msg %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true, html: { multipart: true } do |form| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited this Post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class = "form-section">
    <%= form.label :caption %><br>
    <%= form.text_field :caption %>
  </p>
  
  <% if !form.object.new_record? && form.object.image.present? %> 
    <p class = "form-section">
      <label>Current image</label>
      <%= image_tag @post.image.url(:medium) %>
    </p>
  <% end %>

  <p class = "form-section">
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </p>

  <p class = "form-section">
    <%= form.submit %>
  </p>
<% end %>

app/views/posts/_post.html.erb
<div class = "post">
    <h3><%= post.caption %></h3>
    <div class = "post-field">
        <%= image_tag post.image.url(:medium) %>
    </div>
    <div class = "post-field">
        <%= link_to "Edit", edit_post_path(post) %>
        <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure to delete?" } %>
    </div>
</div>

app/views/posts/edit.html.erb
<div class = "main-button">
    <%= link_to "All Posts", posts_path %>
</div>
<div class = "edit-post">
    <%= render partial: "posts/form", locals: { post: @post } %>
</div>

app/views/posts/index.html.erb
<div>
    <div class = "main-button">
        <%= link_to "Add Post", new_post_path %>
    </div>
    <div id = "posts" class = "index__posts">
        <%= render @posts %>
    </div>
</div>
<%= will_paginate @posts %>

app/views/posts/index.js.erb
$('#posts').append('<%= j render(@posts) %>');
$('.pagination').replaceWith('<%= j will_paginate(@posts) %>');

app/views/posts/new.html.erb
<div class = "main-button">
    <%= link_to "All Posts", posts_path %>
</div>
<div class = "new-post">
    <%= render partial: "posts/form", locals: { post: @post } %>
</div>